### ISSUE TITLE
Stellar.exe is not included here

### ISSUE THREAD

**Issue by osmithy** [treeoftenere/Stellar#1]
The readme file says to download and open Stellar.exe, but where does one find it?

**Comment by sfranzyshen** [comment]
seams they are releasing archives via the releases https://github.com/treeoftenere/Stellar/releases

**Comment by mcslee** [comment]
FYI - the Stellar build was never fully completed and is now defunct. The reference for the software version run at Burning Man 2018 is at https://github.com/treeoftenere/Tenere
